//
//  WeatherApi.swift
//  OpenWeatherKit
//
//  Created by maxime marinel on 03/11/2017.
//  Copyright © 2017 OpenWeatherKit. All rights reserved.
//

import Foundation

/**
  WeatherError generated by the Kit
*/
public enum WeatherError: Error {
    /// invalid data from api call 
    case invalidData
}

/**
    All query output are wrapped into this Enum
*/
public enum Result<T> {
    /**
        Success Result
        - Parameter T: T can be Weather of Forecast struct
    */
    case success(T)
    /**
        Error case
        - Parameter Error?: error can be nil when error are unknown
    */
    case error(Error?)
}

protocol WeatherApiProtocol {
    var key: String {get}
    var endpoint: String {get}
    var version: String {get}
    var urlSession: URLSessionProtocol {get}
    var defaultParameters: [URLQueryItem] {get}

    func getEndpoint() -> String
}

public protocol WeatherApiWeatherProtocol {
    func getWeatherFor(lat: String, lon: String, completion: @escaping (Result<Weather>) -> Void)
    func getWeatherFor(cityId id: Int, completion: @escaping (Result<Weather>) -> Void)
}

public protocol WeatherApiForecastProtocol {
    func getForecastFor(lat: String, lon: String, completion: @escaping (Result<Forecast>) -> Void)
    func getForecastFor(cityId id: Int, completion: @escaping (Result<Forecast>) -> Void)
}

/**
    Main class
*/
public class WeatherApi: WeatherApiProtocol {
    /// OpenWeatherMap key
    var key: String
    /// OpenWeatherMap endpoint
    var endpoint: String = "https://api.openweathermap.org/data"
    /// OpenWeatherMap version for API
    var version: String = "2.5"
    /// URLSession used for query
    var urlSession: URLSessionProtocol
    /// defaultParameters added to all query
    var defaultParameters: [URLQueryItem] = []

    /**
        Init kit

        - Parameter key: OpenWeatherMap Key
        - Parameter urlSession: URLSession used for query
    */
    public init(key: String, urlSession: URLSessionProtocol) {
        self.key = key
        self.urlSession = urlSession
        self.defaultParameters.append(URLQueryItem(name: "APPID", value: key))
    }

    /**
        Init kit

        - Parameter key: OpenWeatherMap Key
    */
    public convenience init(key: String) {
        self.init(key: key, urlSession: URLSession.shared)
    }

    /**
        - Returns: The full endpoint string with endpoint and version
    */ 
    func getEndpoint() -> String {
        return "\(endpoint)/\(version)/"
    }

    /**
        Add defaultParameter for all query
    */
    func addDefaultParameter(name: String, value: String) {
        defaultParameters.append(URLQueryItem(name: name, value: value))
    }

    /**
        Send request 
    */
    private func send<T: Codable>(to endpoint: String, with parameters: [String: Any], completion: @escaping (Result<T>) -> Void) {
        var urlComponents = URLComponents(string: "\(getEndpoint())\(endpoint)")!
        urlComponents.queryItems = defaultParameters
        for (key, value) in parameters {
            urlComponents.queryItems?.append(URLQueryItem(name: key, value: (String(describing: value))))
        }

        urlSession.dataTask(with: urlComponents.url!) { data, response, error in
            guard let data = data else {
                completion(Result.error(WeatherError.invalidData))
                return
            }
            do {
                let decoder = JSONDecoder()
                let weather = try decoder.decode(T.self, from: data)
                completion(Result.success(weather))
            } catch let error {
                completion(Result.error(error))
            }
            }.resume()
    }
}

/**
    Extension for all weather endpoint
*/
extension WeatherApi: WeatherApiWeatherProtocol {
    /**
        Retrieve weather by latitude and longitude

        - Parameter lat: latitude must be between 0 and 90
        - Parameter lon: longitude must be between -180 and 180
        - Parameter completion: Result of api call
    */
    public func getWeatherFor(lat: String, lon: String, completion: @escaping (Result<Weather>) -> Void) {
        send(to: "weather", with: ["lat": lat, "lon": lon], completion: completion)
    }
    /**
        Retrieve weather by OpenWeatherMap city ID

        - Parameter id:  internal id of OpenWeatherMap
        - Parameter completion: Result of api call
        - Remark: City id can be found : http://openweathermap.org/help/city_list.txt or in response result
    */
    public func getWeatherFor(cityId id: Int, completion: @escaping (Result<Weather>) -> Void) {
        send(to: "weather", with: ["id": id], completion: completion)
    }
}

/**
    Extension for all forecast endpoint
*/
extension WeatherApi: WeatherApiForecastProtocol {
    /**
        Retrieve forecast by latitude and longitude

        - Parameter lat: latitude must be between 0 and 90
        - Parameter lon: longitude must be between -180 and 180
        - Parameter completion: Result of api call
    */
    public func getForecastFor(lat: String, lon: String, completion: @escaping (Result<Forecast>) -> Void) {
        send(to: "forecast", with: ["lat": lat, "lon": lon], completion: completion)
    }
    /**
        Retrieve forecast by OpenWeatherMap city ID

        - Parameter id:  internal id of OpenWeatherMap
        - Parameter completion: Result of api call
        - Remark: City id can be found : http://openweathermap.org/help/city_list.txt or in response result
    */
    public func getForecastFor(cityId id: Int, completion: @escaping (Result<Forecast>) -> Void) {
        send(to: "forecast", with: ["id": id], completion: completion)
    }
}
