# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

before_all do
	swiftlint(mode: "autocorrect")
end

platform :ios do
  desc "Test ios"
  lane :test do
  	run_tests(scheme: "OpenWeatherKit-iOS")
  end
end

platform :tvos do
  desc "Test tvos"
  lane :test do
  	run_tests(scheme: "OpenWeatherKit-tvOS")
  end
end

platform :mac do
  desc "Test macos"
  lane :test do
  	run_tests(scheme: "OpenWeatherKit-macOS")
  end
end
